tap "homebrew/core"
tap "homebrew/bundle"
tap "caskroom/cask"
brew "automake"
brew "chruby"
brew "dfu-programmer"
brew "gdbm"
brew "gh"
brew "git"
brew "git-crypt"
brew "gnupg"
brew "libyaml"
brew "mas"
brew "nmap"
brew "readline"
brew "ruby-install"
brew "ssh-copy-id"
brew "tor"
brew "wget"
brew "heroku/brew/heroku"
cask "ableton-live-suite"
cask "android-studio"
cask "atom"
cask "battle-net"
cask "discord"
cask "firefox"
cask "google-chrome"
cask "minecraft"
cask "opera"
cask "sketch"
cask "steam"
cask "slack"
cask "transmission"
cask "twitch"
cask "vagrant"
cask "virtualbox"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "Pixelmator", id: 407963104
mas "Xcode", id: 497799835
