# ~/.tmuxinator/default.yml

name: default
root: ~/

# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: sudo /etc/rc.d/mysqld start

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

windows:
  - main:
      layout: 64d6,181x55,0,0{90x55,0,0,0,90x55,91,0,1}
      panes:
        - tmux rename-window main
        - # empty zsh
  - dev:
      layout: 8a25,181x55,0,0[181x41,0,0,2,181x13,0,42{90x13,0,42,4,90x13,91,42,5}]
      panes:
        - vim -O2
        - tmux rename-window dev
        - # empty zsh
