# ~/.tmuxinator/default.yml
# you can make as many tabs as you wish...

project_name: Default
project_root: ~/
tabs:
  - dev:
      layout: 5ec5,181x55,0,0{90x55,0,0[90x27,0,0,90x27,0,28],90x55,91,0[90x27,91,0,90x27,91,28]}
      panes:
        - earthquake
        - irssi
        - # empty zsh
        - vim
