# ~/.tmuxinator/default.yml
# you can make as many tabs as you wish...

project_name: Default
project_root: ~/
tabs:
  - dev:
      layout: 4fe3,181x55,0,0{90x55,0,0[90x13,0,0,90x41,0,14],90x55,91,0}
      panes:
        - earthquake
        - # empty zsh
        - vim
